version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "type/chore"
      - "priority/medium"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "type/chore"
      - "priority/low"

  - package-ecosystem: "gomod"
    directory: "/tui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "type/chore"
      - "priority/low"
