#Requires -Version 5.1
<#
.SYNOPSIS
    Generate docker-compose files for N accounts.
.DESCRIPTION
    Reads NUM_ACCOUNTS and IMAGE_TAG from .env (or environment) and writes:
      docker-compose.yml          Base config (Tier A: shared source)
      docker-compose.worktree.yml Tier B override (per-account worktrees)
      docker-compose.linux.yml    Linux UID/GID override
.EXAMPLE
    .\scripts\generate-compose.ps1
    .\scripts\generate-compose.ps1 -NumAccounts 4
#>
[CmdletBinding()]
param(
    [int]$NumAccounts = 0,
    [string]$ImageTag = ''
)

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ProjectRoot = Split-Path -Parent $ScriptDir

Import-Module (Join-Path $ScriptDir 'ClaudeDocker.psm1') -Force

# --- Read configuration -------------------------------------------------------

$envFile = Join-Path $ProjectRoot '.env'
$envData = @{}
if (Test-Path $envFile) {
    $envData = Read-EnvFile -Path $envFile
}

if ($NumAccounts -eq 0) {
    $fromEnv = $envData['NUM_ACCOUNTS']
    if ($fromEnv -and $fromEnv -match '^\d+$') {
        $NumAccounts = [int]$fromEnv
    } else {
        $NumAccounts = 2
    }
}

if ([string]::IsNullOrEmpty($ImageTag)) {
    $fromEnv = $envData['IMAGE_TAG']
    if ($fromEnv) {
        $ImageTag = $fromEnv
    } else {
        $ImageTag = 'latest'
    }
}

if ($NumAccounts -lt 1 -or $NumAccounts -gt 26) {
    Write-Error "NUM_ACCOUNTS must be between 1 and 26 (got: $NumAccounts)"
    exit 1
}

function ConvertTo-Letter([int]$Index) {
    # 1 -> a, 2 -> b, ..., 26 -> z
    [char](96 + $Index)
}

function ConvertTo-UpperLetter([int]$Index) {
    # 1 -> A, 2 -> B, ..., 26 -> Z
    [char](64 + $Index)
}

# --- Generate docker-compose.yml ---------------------------------------------

function New-BaseCompose {
    $outFile = Join-Path $ProjectRoot 'docker-compose.yml'
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine('# docker-compose.yml — Base config (Tier A: shared source)')
    [void]$sb.AppendLine('# Generated by scripts/generate-compose.ps1 — do not edit manually.')
    [void]$sb.AppendLine('# Regenerate: scripts/generate-compose.ps1')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('services:')

    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        $upper  = ConvertTo-UpperLetter $i
        $svc    = "claude-$letter"

        [void]$sb.AppendLine("  ${svc}:")

        if ($i -eq 1) {
            [void]$sb.AppendLine('    build:')
            [void]$sb.AppendLine('      context: .')
            [void]$sb.AppendLine('      args:')
            [void]$sb.AppendLine('        CLAUDE_CODE_VERSION: ${CLAUDE_CODE_VERSION:-}')
        }

        [void]$sb.AppendLine("    image: claude-code-base:`${IMAGE_TAG:-$ImageTag}")

        if ($i -gt 1) {
            [void]$sb.AppendLine('    depends_on:')
            [void]$sb.AppendLine('      - claude-a')
        }

        [void]$sb.AppendLine('    working_dir: ${CONTAINER_PROJECT_DIR:-/project}')
        [void]$sb.AppendLine('    stdin_open: true')
        [void]$sb.AppendLine('    tty: true')
        [void]$sb.AppendLine('    volumes:')
        [void]$sb.AppendLine('      - ${PROJECT_DIR}:${CONTAINER_PROJECT_DIR:-/project}')
        [void]$sb.AppendLine("      - `${HOME}/.claude-state/account-${letter}:/home/node/.claude")
        [void]$sb.AppendLine('      - ${HOME}/.claude:/home/node/.claude-host:ro')
        [void]$sb.AppendLine('      - ${GH_CONFIG_DIR:-${HOME}/.config/gh}:/home/node/.config/gh:ro')
        [void]$sb.AppendLine("      - node_modules_${letter}:`${CONTAINER_PROJECT_DIR:-/project}/node_modules")
        [void]$sb.AppendLine('    environment:')
        [void]$sb.AppendLine('      - TERM=xterm-256color')
        [void]$sb.AppendLine('      - CLAUDE_CONFIG_DIR=/home/node/.claude')
        [void]$sb.AppendLine('      - CLAUDE_CONFIG_SOURCE=${CLAUDE_CONFIG_SOURCE:-}')
        [void]$sb.AppendLine('      - NODE_OPTIONS=--max-old-space-size=4096')
        [void]$sb.AppendLine("      - ANTHROPIC_API_KEY=`${CLAUDE_API_KEY_${upper}:-}")
        [void]$sb.AppendLine('      - GH_TOKEN=${GH_TOKEN:-}')
        [void]$sb.AppendLine('      - GIT_USER_NAME=${GIT_USER_NAME:-}')
        [void]$sb.AppendLine('      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-}')
        [void]$sb.AppendLine('    deploy:')
        [void]$sb.AppendLine('      resources:')
        [void]$sb.AppendLine('        limits:')
        [void]$sb.AppendLine('          cpus: "2"')
        [void]$sb.AppendLine('          memory: 4G')
        [void]$sb.AppendLine('        reservations:')
        [void]$sb.AppendLine('          cpus: "1"')
        [void]$sb.AppendLine('          memory: 2G')
        [void]$sb.AppendLine('    command: ["sleep", "infinity"]')

        if ($i -lt $NumAccounts) {
            [void]$sb.AppendLine('')
        }
    }

    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('volumes:')
    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        [void]$sb.AppendLine("  node_modules_${letter}:")
    }

    Write-EnvContent -Path $outFile -Content $sb.ToString()
    Write-LogInfo "Generated: $outFile ($NumAccounts services)"
}

# --- Generate docker-compose.worktree.yml ------------------------------------

function New-WorktreeCompose {
    $outFile = Join-Path $ProjectRoot 'docker-compose.worktree.yml'
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine('# docker-compose.worktree.yml')
    [void]$sb.AppendLine('# Generated by scripts/generate-compose.ps1 — do not edit manually.')
    [void]$sb.AppendLine('# Usage: docker compose -f docker-compose.yml -f docker-compose.worktree.yml up')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('services:')

    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        $upper  = ConvertTo-UpperLetter $i
        $svc    = "claude-$letter"

        [void]$sb.AppendLine("  ${svc}:")
        [void]$sb.AppendLine("    working_dir: `${CONTAINER_PROJECT_DIR_${upper}:-/project-$letter}")
        [void]$sb.AppendLine('    volumes:')
        [void]$sb.AppendLine("      - `${PROJECT_DIR_${upper}}:`${CONTAINER_PROJECT_DIR_${upper}:-/project-$letter}")
        [void]$sb.AppendLine("      - node_modules_${letter}:`${CONTAINER_PROJECT_DIR_${upper}:-/project-$letter}/node_modules")

        if ($i -lt $NumAccounts) {
            [void]$sb.AppendLine('')
        }
    }

    Write-EnvContent -Path $outFile -Content $sb.ToString()
    Write-LogInfo "Generated: $outFile ($NumAccounts services)"
}

# --- Generate docker-compose.linux.yml ----------------------------------------

function New-LinuxCompose {
    $outFile = Join-Path $ProjectRoot 'docker-compose.linux.yml'
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine('# docker-compose.linux.yml')
    [void]$sb.AppendLine('# Generated by scripts/generate-compose.ps1 — do not edit manually.')
    [void]$sb.AppendLine('# Usage: docker compose -f docker-compose.yml -f docker-compose.linux.yml up')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('services:')

    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        $svc    = "claude-$letter"

        [void]$sb.AppendLine("  ${svc}:")
        [void]$sb.AppendLine('    user: "${UID}:${GID}"')
        [void]$sb.AppendLine('    environment:')
        [void]$sb.AppendLine('      - HOME=/home/node')

        if ($i -lt $NumAccounts) {
            [void]$sb.AppendLine('')
        }
    }

    Write-EnvContent -Path $outFile -Content $sb.ToString()
    Write-LogInfo "Generated: $outFile ($NumAccounts services)"
}

# --- Main ---------------------------------------------------------------------

Write-LogInfo "Generating compose files for $NumAccounts account(s)..."
New-BaseCompose
New-WorktreeCompose
New-LinuxCompose
Write-LogSuccess 'Done.'
