#Requires -Version 5.1
<#
.SYNOPSIS
    Generate docker-compose files for N accounts.
.DESCRIPTION
    Reads NUM_ACCOUNTS and IMAGE_TAG from .env (or environment) and writes:
      docker-compose.yml          Base config (Tier A: shared source)
      docker-compose.worktree.yml Tier B override (per-account worktrees)
      docker-compose.linux.yml    Linux UID/GID override
.EXAMPLE
    .\scripts\generate-compose.ps1
    .\scripts\generate-compose.ps1 -NumAccounts 4
#>
[CmdletBinding()]
param(
    [int]$NumAccounts = 0,
    [string]$ImageTag = ''
)

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ProjectRoot = Split-Path -Parent $ScriptDir

Import-Module (Join-Path $ScriptDir 'ClaudeDocker.psm1') -Force
. (Join-Path $ScriptDir 'lib' 'index.ps1')

# --- Read configuration -------------------------------------------------------

$envFile = Join-Path $ProjectRoot '.env'
$envData = @{}
if (Test-Path $envFile) {
    $envData = Read-EnvFile -Path $envFile
}

if ($NumAccounts -eq 0) {
    $fromEnv = $envData['NUM_ACCOUNTS']
    if ($fromEnv -and $fromEnv -match '^\d+$') {
        $NumAccounts = [int]$fromEnv
    } else {
        $NumAccounts = 2
    }
}

if ([string]::IsNullOrEmpty($ImageTag)) {
    $fromEnv = $envData['IMAGE_TAG']
    if ($fromEnv) {
        $ImageTag = $fromEnv
    } else {
        # Fall back to the repo-root VERSION file — single source of truth
        # shared with install.ps1 and the "Bumping the Base Image" README
        # procedure. Final fallback is 'latest' if VERSION is absent.
        $versionFile = Join-Path $ProjectRoot 'VERSION'
        if (Test-Path $versionFile) {
            $ImageTag = (Get-Content $versionFile -TotalCount 1).Trim()
        }
        if ([string]::IsNullOrEmpty($ImageTag)) {
            $ImageTag = 'latest'
        }
    }
}

if ($NumAccounts -lt 1 -or $NumAccounts -gt 702) {
    Write-Error "NUM_ACCOUNTS must be between 1 and 702 (got: $NumAccounts)"
    exit 1
}

# Container resource envelope (override via .env or host env). Defaults
# reproduce the historical hardcoded values so existing installs see no
# behavior change after regenerating.
function Resolve-EnvOrDefault([string]$Key, [string]$Default) {
    $val = [Environment]::GetEnvironmentVariable($Key)
    if (-not [string]::IsNullOrEmpty($val)) { return $val }
    if ($envData.ContainsKey($Key) -and -not [string]::IsNullOrEmpty($envData[$Key])) {
        return $envData[$Key]
    }
    return $Default
}
$CpuLimit       = Resolve-EnvOrDefault 'CONTAINER_CPU_LIMIT' '2'
$CpuReservation = Resolve-EnvOrDefault 'CONTAINER_CPU_RESERVATION' '1'
$MemLimit       = Resolve-EnvOrDefault 'CONTAINER_MEM_LIMIT' '4G'
$MemReservation = Resolve-EnvOrDefault 'CONTAINER_MEM_RESERVATION' '2G'

# Thin wrappers around the shared helpers in lib/index.ps1 so legacy call
# sites below keep working without rewriting each loop. Both helpers accept
# indices 1..702 and throw out-of-range otherwise.
function ConvertTo-Letter([int]$Index) {
    return Get-AccountLetter -Index $Index
}

function ConvertTo-UpperLetter([int]$Index) {
    return Get-AccountLetterUpper -Index $Index
}

# --- Generate docker-compose.yml ---------------------------------------------

function New-BaseCompose {
    $outFile = Join-Path $ProjectRoot 'docker-compose.yml'
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine('# docker-compose.yml — Base config (Tier A: shared source)')
    [void]$sb.AppendLine('# Generated by scripts/generate-compose.ps1 — do not edit manually.')
    [void]$sb.AppendLine('# Regenerate: scripts/generate-compose.ps1')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('services:')

    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        $upper  = ConvertTo-UpperLetter $i
        $svc    = "claude-$letter"

        [void]$sb.AppendLine("  ${svc}:")

        if ($i -eq 1) {
            [void]$sb.AppendLine('    build:')
            [void]$sb.AppendLine('      context: .')
            [void]$sb.AppendLine('      args:')
            [void]$sb.AppendLine('        CLAUDE_CODE_VERSION: ${CLAUDE_CODE_VERSION:-}')
        }

        [void]$sb.AppendLine("    image: claude-code-base:`${IMAGE_TAG:-$ImageTag}")

        if ($i -gt 1) {
            [void]$sb.AppendLine('    depends_on:')
            [void]$sb.AppendLine('      - claude-a')
        }

        [void]$sb.AppendLine('    working_dir: ${CONTAINER_PROJECT_DIR:-/project}')
        [void]$sb.AppendLine('    stdin_open: true')
        [void]$sb.AppendLine('    tty: true')
        [void]$sb.AppendLine('    volumes:')
        [void]$sb.AppendLine('      - ${PROJECT_DIR}:${CONTAINER_PROJECT_DIR:-/project}')
        [void]$sb.AppendLine("      - `${HOME}/.claude-state/account-${letter}:/home/node/.claude")
        [void]$sb.AppendLine('      - ${HOME}/.claude:/home/node/.claude-host:ro')
        [void]$sb.AppendLine('      - ${GH_CONFIG_DIR:-${HOME}/.config/gh}:/home/node/.config/gh:ro')
        [void]$sb.AppendLine("      - node_modules_${letter}:`${CONTAINER_PROJECT_DIR:-/project}/node_modules")
        [void]$sb.AppendLine('    environment:')
        [void]$sb.AppendLine('      - TERM=xterm-256color')
        [void]$sb.AppendLine('      - CLAUDE_CONFIG_DIR=/home/node/.claude')
        [void]$sb.AppendLine('      - CLAUDE_CONFIG_SOURCE=${CLAUDE_CONFIG_SOURCE:-}')
        [void]$sb.AppendLine('      - CLAUDE_NORMALIZE_CRLF=${CLAUDE_NORMALIZE_CRLF:-}')
        [void]$sb.AppendLine('      - NODE_OPTIONS=--max-old-space-size=4096')
        # Only emit ANTHROPIC_API_KEY when CLAUDE_API_KEY_<LETTER> is set at
        # generate time. Path A (OAuth) users have no value; emitting
        # ANTHROPIC_API_KEY= with an empty string makes the SDK prefer the
        # empty env var over .credentials.json in the mounted state dir.
        $keyVarName = "CLAUDE_API_KEY_${upper}"
        $keyValue = [Environment]::GetEnvironmentVariable($keyVarName)
        if (-not [string]::IsNullOrEmpty($keyValue)) {
            [void]$sb.AppendLine("      - ANTHROPIC_API_KEY=`${CLAUDE_API_KEY_${upper}}")
        }
        [void]$sb.AppendLine('      - GH_TOKEN=${GH_TOKEN:-}')
        [void]$sb.AppendLine('      - GIT_USER_NAME=${GIT_USER_NAME:-}')
        [void]$sb.AppendLine('      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-}')
        [void]$sb.AppendLine('    deploy:')
        [void]$sb.AppendLine('      resources:')
        [void]$sb.AppendLine('        limits:')
        [void]$sb.AppendLine("          cpus: `"$CpuLimit`"")
        [void]$sb.AppendLine("          memory: $MemLimit")
        [void]$sb.AppendLine('        reservations:')
        [void]$sb.AppendLine("          cpus: `"$CpuReservation`"")
        [void]$sb.AppendLine("          memory: $MemReservation")
        [void]$sb.AppendLine('    command: ["sleep", "infinity"]')

        if ($i -lt $NumAccounts) {
            [void]$sb.AppendLine('')
        }
    }

    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('volumes:')
    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        [void]$sb.AppendLine("  node_modules_${letter}:")
    }

    Write-EnvContent -Path $outFile -Content $sb.ToString()
    Write-LogInfo "Generated: $outFile ($NumAccounts services)"
}

# --- Generate docker-compose.worktree.yml ------------------------------------

function New-WorktreeCompose {
    $outFile = Join-Path $ProjectRoot 'docker-compose.worktree.yml'
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine('# docker-compose.worktree.yml')
    [void]$sb.AppendLine('# Generated by scripts/generate-compose.ps1 — do not edit manually.')
    [void]$sb.AppendLine('# Usage: docker compose -f docker-compose.yml -f docker-compose.worktree.yml up')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('services:')

    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        $upper  = ConvertTo-UpperLetter $i
        $svc    = "claude-$letter"

        [void]$sb.AppendLine("  ${svc}:")
        [void]$sb.AppendLine("    working_dir: `${CONTAINER_PROJECT_DIR_${upper}:-/project-$letter}")
        [void]$sb.AppendLine('    volumes:')
        [void]$sb.AppendLine("      - `${PROJECT_DIR_${upper}}:`${CONTAINER_PROJECT_DIR_${upper}:-/project-$letter}")
        [void]$sb.AppendLine("      - node_modules_${letter}:`${CONTAINER_PROJECT_DIR_${upper}:-/project-$letter}/node_modules")

        if ($i -lt $NumAccounts) {
            [void]$sb.AppendLine('')
        }
    }

    Write-EnvContent -Path $outFile -Content $sb.ToString()
    Write-LogInfo "Generated: $outFile ($NumAccounts services)"
}

# --- Generate docker-compose.linux.yml ----------------------------------------

function New-LinuxCompose {
    $outFile = Join-Path $ProjectRoot 'docker-compose.linux.yml'
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine('# docker-compose.linux.yml')
    [void]$sb.AppendLine('# Generated by scripts/generate-compose.ps1 — do not edit manually.')
    [void]$sb.AppendLine('# Usage: docker compose -f docker-compose.yml -f docker-compose.linux.yml up')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('services:')

    for ($i = 1; $i -le $NumAccounts; $i++) {
        $letter = ConvertTo-Letter $i
        $svc    = "claude-$letter"

        [void]$sb.AppendLine("  ${svc}:")
        [void]$sb.AppendLine('    user: "${UID}:${GID}"')
        [void]$sb.AppendLine('    environment:')
        [void]$sb.AppendLine('      - HOME=/home/node')

        if ($i -lt $NumAccounts) {
            [void]$sb.AppendLine('')
        }
    }

    Write-EnvContent -Path $outFile -Content $sb.ToString()
    Write-LogInfo "Generated: $outFile ($NumAccounts services)"
}

# --- Main ---------------------------------------------------------------------

Write-LogInfo "Generating compose files for $NumAccounts account(s)..."
New-BaseCompose
New-WorktreeCompose
New-LinuxCompose
Write-LogSuccess 'Done.'
