#!/usr/bin/env bash
# generate-compose.sh — Generate docker-compose files for N accounts.
#
# Reads NUM_ACCOUNTS and IMAGE_TAG from .env (or environment) and writes:
#   docker-compose.yml          Base config (Tier A: shared source)
#   docker-compose.worktree.yml Tier B override (per-account worktrees)
#   docker-compose.linux.yml    Linux UID/GID override
#
# Usage:
#   scripts/generate-compose.sh              # Uses .env defaults
#   NUM_ACCOUNTS=4 scripts/generate-compose.sh  # Override via env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/parse_env.sh
. "$SCRIPT_DIR/lib/parse_env.sh"
# shellcheck source=lib/index.sh
. "$SCRIPT_DIR/lib/index.sh"

# --- Read configuration -------------------------------------------------------

# Values already in the caller's environment win over .env entries.
load_env_file "$PROJECT_ROOT/.env"

NUM_ACCOUNTS="${NUM_ACCOUNTS:-2}"

# IMAGE_TAG defaults come from the repo-root VERSION file — single source of
# truth shared with install.sh and the "Bumping the Base Image" README
# procedure. Falls back to "latest" if VERSION is missing (e.g. the user is
# running the script from an older clone or a sparse checkout).
if [[ -z "${IMAGE_TAG:-}" ]]; then
    if [[ -f "$PROJECT_ROOT/VERSION" ]]; then
        IMAGE_TAG="$(head -n1 "$PROJECT_ROOT/VERSION" | tr -d '[:space:]')"
    fi
    IMAGE_TAG="${IMAGE_TAG:-latest}"
fi

# Validate. Practical upper bound is "zz" (702) from Excel-style letter
# enumeration; keep the cap well below that to catch typos like 2600.
if [[ "$NUM_ACCOUNTS" -lt 1 || "$NUM_ACCOUNTS" -gt 702 ]]; then
    echo "Error: NUM_ACCOUNTS must be between 1 and 702 (got: $NUM_ACCOUNTS)" >&2
    exit 1
fi

# Container resource envelope (override via .env or host env). Defaults
# reproduce the historical hardcoded values so existing installs see no
# behavior change after regenerating.
CPU_LIMIT="${CONTAINER_CPU_LIMIT:-2}"
CPU_RESERVATION="${CONTAINER_CPU_RESERVATION:-1}"
MEM_LIMIT="${CONTAINER_MEM_LIMIT:-4G}"
MEM_RESERVATION="${CONTAINER_MEM_RESERVATION:-2G}"

# index_to_letter and index_to_upper provided by scripts/lib/index.sh.

# --- Generate docker-compose.yml ---------------------------------------------

generate_base() {
    local outfile="$PROJECT_ROOT/docker-compose.yml"
    {
        echo "# docker-compose.yml — Base config (Tier A: shared source)"
        echo "# Generated by scripts/generate-compose.sh — do not edit manually."
        echo "# Regenerate: scripts/generate-compose.sh"
        echo ""
        echo "services:"

        for i in $(seq 1 "$NUM_ACCOUNTS"); do
            local letter
            letter=$(index_to_letter "$i")
            local upper
            upper=$(index_to_upper "$i")
            local svc="claude-${letter}"

            echo "  ${svc}:"

            # Only the first service builds the image
            if [[ "$i" -eq 1 ]]; then
                echo "    build:"
                echo "      context: ."
                echo "      args:"
                echo "        CLAUDE_CODE_VERSION: \${CLAUDE_CODE_VERSION:-}"
            fi

            echo "    image: claude-code-base:\${IMAGE_TAG:-${IMAGE_TAG}}"

            # All services after the first depend on claude-a (for build ordering)
            if [[ "$i" -gt 1 ]]; then
                echo "    depends_on:"
                echo "      - claude-a"
            fi

            echo "    working_dir: \${CONTAINER_PROJECT_DIR:-/project}"
            echo "    stdin_open: true"
            echo "    tty: true"
            echo "    volumes:"
            echo "      - \${PROJECT_DIR}:\${CONTAINER_PROJECT_DIR:-/project}"
            echo "      - \${HOME}/.claude-state/account-${letter}:/home/node/.claude"
            echo "      - \${HOME}/.claude:/home/node/.claude-host:ro"
            echo "      - \${GH_CONFIG_DIR:-\${HOME}/.config/gh}:/home/node/.config/gh:ro"
            echo "      - node_modules_${letter}:\${CONTAINER_PROJECT_DIR:-/project}/node_modules"
            echo "    environment:"
            echo "      - TERM=xterm-256color"
            echo "      - TZ=\${TZ:-UTC}"
            echo "      - CLAUDE_CONFIG_DIR=/home/node/.claude"
            echo "      - CLAUDE_CONFIG_SOURCE=\${CLAUDE_CONFIG_SOURCE:-}"
            echo "      - CLAUDE_NORMALIZE_CRLF=\${CLAUDE_NORMALIZE_CRLF:-}"
            echo "      - NODE_OPTIONS=--max-old-space-size=4096"
            # Only emit ANTHROPIC_API_KEY when CLAUDE_API_KEY_<LETTER> is
            # set at generate time. Path A (OAuth) users have no value;
            # emitting ANTHROPIC_API_KEY= with an empty string makes the
            # SDK prefer the empty env var over .credentials.json.
            local key_var="CLAUDE_API_KEY_${upper}"
            if [[ -n "${!key_var:-}" ]]; then
                echo "      - ANTHROPIC_API_KEY=\${CLAUDE_API_KEY_${upper}}"
            fi
            echo "      - GH_TOKEN=\${GH_TOKEN:-}"
            echo "      - GIT_USER_NAME=\${GIT_USER_NAME:-}"
            echo "      - GIT_USER_EMAIL=\${GIT_USER_EMAIL:-}"
            echo "    deploy:"
            echo "      resources:"
            echo "        limits:"
            echo "          cpus: \"${CPU_LIMIT}\""
            echo "          memory: ${MEM_LIMIT}"
            echo "        reservations:"
            echo "          cpus: \"${CPU_RESERVATION}\""
            echo "          memory: ${MEM_RESERVATION}"
            echo "    command: [\"sleep\", \"infinity\"]"

            # Blank line between services (but not after the last one)
            if [[ "$i" -lt "$NUM_ACCOUNTS" ]]; then
                echo ""
            fi
        done

        echo ""
        echo "volumes:"
        for i in $(seq 1 "$NUM_ACCOUNTS"); do
            local letter
            letter=$(index_to_letter "$i")
            echo "  node_modules_${letter}:"
        done
    } > "$outfile"

    echo "Generated: $outfile ($NUM_ACCOUNTS services)"
}

# --- Generate docker-compose.worktree.yml ------------------------------------

generate_worktree() {
    local outfile="$PROJECT_ROOT/docker-compose.worktree.yml"
    {
        echo "# docker-compose.worktree.yml"
        echo "# Generated by scripts/generate-compose.sh — do not edit manually."
        echo "# Usage: docker compose -f docker-compose.yml -f docker-compose.worktree.yml up"
        echo ""
        echo "services:"

        for i in $(seq 1 "$NUM_ACCOUNTS"); do
            local letter
            letter=$(index_to_letter "$i")
            local upper
            upper=$(index_to_upper "$i")
            local svc="claude-${letter}"

            echo "  ${svc}:"
            echo "    working_dir: \${CONTAINER_PROJECT_DIR_${upper}:-/project-${letter}}"
            echo "    volumes:"
            echo "      - \${PROJECT_DIR_${upper}}:\${CONTAINER_PROJECT_DIR_${upper}:-/project-${letter}}"
            echo "      - node_modules_${letter}:\${CONTAINER_PROJECT_DIR_${upper}:-/project-${letter}}/node_modules"

            if [[ "$i" -lt "$NUM_ACCOUNTS" ]]; then
                echo ""
            fi
        done
    } > "$outfile"

    echo "Generated: $outfile ($NUM_ACCOUNTS services)"
}

# --- Generate docker-compose.linux.yml ----------------------------------------

generate_linux() {
    local outfile="$PROJECT_ROOT/docker-compose.linux.yml"
    {
        echo "# docker-compose.linux.yml"
        echo "# Generated by scripts/generate-compose.sh — do not edit manually."
        echo "# Usage: docker compose -f docker-compose.yml -f docker-compose.linux.yml up"
        echo ""
        echo "services:"

        for i in $(seq 1 "$NUM_ACCOUNTS"); do
            local letter
            letter=$(index_to_letter "$i")
            local svc="claude-${letter}"

            echo "  ${svc}:"
            echo "    user: \"\${UID}:\${GID}\""
            echo "    environment:"
            echo "      - HOME=/home/node"

            if [[ "$i" -lt "$NUM_ACCOUNTS" ]]; then
                echo ""
            fi
        done
    } > "$outfile"

    echo "Generated: $outfile ($NUM_ACCOUNTS services)"
}

# --- Main ---------------------------------------------------------------------

main() {
    echo "Generating compose files for $NUM_ACCOUNTS account(s)..."
    generate_base
    generate_worktree
    generate_linux
    echo "Done."
}

main
